import {ScaledSheet} from 'react-native-size-matters';
import {Colors} from '../../../Theme/colors';
import {Sizes} from '../../../Theme/sizes';
export const styles = ScaledSheet.create({
  mContainer: {
    flex: Sizes.size_1,
  },
  viewFavorite: {
    position: 'absolute',
    zIndex: Sizes.size_1,
    top: '24@vs',
    right: '16@s',
  },
  mArrow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    position: 'absolute',
    top: '120@vs',
  },
  arrowLeft: {
    width: Sizes.size_25,
    height: Sizes.size_50,
    borderBottomRightRadius: Sizes.size_25,
    borderTopRightRadius: Sizes.size_25,
    backgroundColor: Colors.Gray81,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: Sizes.size_20,
    opacity: 0.3,
  },
  arrowRight: {
    width: Sizes.size_25,
    height: Sizes.size_50,
    borderBottomLeftRadius: Sizes.size_25,
    borderTopLeftRadius: Sizes.size_25,
    backgroundColor: Colors.Gray81,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: Sizes.size_20,
    opacity: 0.3,
  },
  mViewColor: {
    width: Sizes.size_50,
    height: Sizes.size_50,
    borderWidth: Sizes.size_2,
    margin: '5@s',
    borderRadius: Sizes.size_15,
    backgroundColor: Colors.Gray51,
  },
  mSize: {
    width: Sizes.size_50,
    height: Sizes.size_50,
    borderWidth: Sizes.size_2,
    margin: '5@s',
    borderRadius: Sizes.size_15,
    backgroundColor: Colors.Gray51,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mBodyView: {
    backgroundColor: Colors.Gray81,
    borderTopLeftRadius: Sizes.size_50,
    borderTopRightRadius: Sizes.size_50,
    alignItems: 'flex-start',
    height: Sizes.size_350,
    overflow: 'hidden',
    marginTop: '16@vs',
  },
  mStar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop:'12@vs'
  },
  btnCart: {
    height: Sizes.size_80,
    position: 'absolute',
    backgroundColor: Colors.Gray11,
    bottom: Sizes.size_0,
    width: '100%',
    borderTopLeftRadius: Sizes.size_30,
    borderTopRightRadius: Sizes.size_30,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
  },
  mTextCLS: {
    fontSize: Sizes.size_18,
    fontStyle: 'italic',
    color: Colors.Gray31,
    marginLeft: '5@s',
    marginTop: '12@vs',
  },
  titleSize: {
    fontSize: Sizes.size_16,
    fontStyle: 'italic',
  },
  mtitleName: {
    fontSize: Sizes.size_22,
    fontStyle: 'italic',
    fontWeight: 'bold',
    color: Colors.Black,
    textAlign: 'center',
    marginTop: '12@vs',
  },
  titlePrice: {
    fontSize: Sizes.size_20,
    fontStyle: 'italic',
    fontWeight: '500',
    color: Colors.White,
    marginLeft:'24@s'
  },
  titlePriceSale:{
    fontSize: Sizes.size_20,
    fontStyle: 'italic',
    fontWeight: '500',
    color: Colors.Gray51,
    marginLeft:'24@s',
    textDecorationLine: 'line-through',
  },
  titleInfo:{
    fontSize: Sizes.size_18,
    fontStyle: 'italic',
    width:'80%',
    marginLeft:'25@s',
    textAlign:'center',
    margin:'12@s'
  }
});
